### ISSUE TITLE
Brak obrazka w sekcji dodatki.

### ISSUE THREAD

**Issue by blabla9311** [majekbezjajek/pizzeria-a-Strongoli#6]
Cześć. Zauważyłem, że w sekcji z dodatkami brakuje obrazka. Zdaje się, że trzeba to poprawić.

**Comment by majekbezjajek** [comment]
Dodaliśmy commit 7ed6228, który naprawił problem.

**Comment by majekbezjajek** [comment]
7ed6228 fixes #6
